### ISSUE TITLE
ERROR: BoundsError()

### ISSUE THREAD

**Issue by dchun** [dfdx/ActiveAppearanceModels.jl#1]
After running the sample script: "multi.jl", I get the following error:

```
ERROR: BoundsError()
```

From the following lines in the train.jl file:

```
 in build_app_model at /ActiveAppearanceModels/src/train.jl:74
 in train at /ActiveAppearanceModels/src/train.jl:192
```

**Comment by dfdx** [comment]
Hmm, this is more interesting, since I cannot reproduce it locally. As an "I feel lucky" attempt, try to pull master of `PiecewiseAffineTransforms` package as well - this is one more package I'm preparing for update in nearest time. 

If this doesn't help, could you please post here an output of `Pkg.status()` so I could inspect differences between mine and yours packages?

**Comment by dchun** [comment]
The following is the output after I pulled from the master branch, which is running the same version prior to removing the `PiecewiseAffineTransforms` package and cloning it from the master repo and it's producing the same error.

Package Status:

```
13 required packages:
 - ActiveAppearanceModels        0.1.1
 - Color                         0.4.8
 - Docile                        0.5.16
 - FaceDatasets                  0.1.2+             master
 - FixedPointNumbers             0.0.10
 - ImageView                     0.1.16
 - Images                        0.4.46
 - Jewel                         1.0.5
 - MAT                           0.2.12
 - MultivariateStats             0.2.1
 - PiecewiseAffineTransforms     0.1.1              master
 - StatsBase                     0.7.1
 - VoronoiDelaunay               0.0.1
34 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Blosc                         0.1.4
 - Cairo                         0.2.29
 - ColorTypes                    0.1.3
 - ColorVectorSpace              0.0.2
 - Colors                        0.5.2
 - Compat                        0.6.0
 - Compose                       0.3.14
 - DataStructures                0.3.12
 - Dates                         0.3.2
 - FactCheck                     0.4.0
 - GeometricalPredicates         0.0.4
 - Graphics                      0.1.0
 - HDF5                          0.5.5
 - Homebrew                      0.1.16
 - HttpCommon                    0.1.2
 - IniFile                       0.2.4
 - Iterators                     0.1.8
 - JSON                          0.4.5
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.10.0
 - MacroTools                    0.2.0
 - Reexport                      0.0.2
 - Requires                      0.1.3
 - SHA                           0.1.1
 - SIUnits                       0.0.5
 - StatsFuns                     0.1.3
 - TexExtensions                 0.0.2
 - Tk                            0.3.6
 - URIParser                     0.0.7
 - Winston                       0.11.12
 - Zlib                          0.1.9
```

**Comment by dfdx** [comment]
I see you use latest registered version of ActiveAppearanceModels.jl, not master. Could you please check it out too? 

Normally I try to keep all tagged packages updated, but you really caught me in a transition period.

**Comment by dchun** [comment]
Just did but getting the same error. The strange thing about the error is that it references a line that doesn't exist in the multi.jl file:

```
while loading /ActiveAppearanceModels/examples/multi.jl, in expression starting on line 56
```

Thanks for all the quick responses btw...

**Comment by dfdx** [comment]
Not sure it's related to your issue, but I've just fixed a bug in my code. Please, pull master and try again. 

If it doesn't work (and I expect it doesn't), please post full backtrace you have. It's really strange that error message points to a totally unrelated line, so any additional information may uncover hidden bugs or inconsistencies . 

Next step would be to create a debug branch with a couple `println`s and see where this error comes from.

**Comment by dchun** [comment]
Here is the full backtrace:

```
ERROR: BoundsError()
 in build_app_model at /Users/davidchun/.julia/v0.3/ActiveAppearanceModels/src/train.jl:74
 in train at /Users/davidchun/.julia/v0.3/ActiveAppearanceModels/src/train.jl:192
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/davidchun/code/julia/aam/examples/multi.jl, in expression starting on line 56
```

And the `Pkg.status()`:

```
13 required packages:
 - ActiveAppearanceModels        0.1.1+             master
 - Color                         0.4.8
 - Docile                        0.5.16
 - FaceDatasets                  0.1.2+             master
 - FixedPointNumbers             0.0.10
 - ImageView                     0.1.16
 - Images                        0.4.46
 - Jewel                         1.0.5
 - MAT                           0.2.12
 - MultivariateStats             0.2.1
 - PiecewiseAffineTransforms     0.1.1              master
 - StatsBase                     0.7.1
 - VoronoiDelaunay               0.0.1
34 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Blosc                         0.1.4
 - Cairo                         0.2.29
 - ColorTypes                    0.1.3
 - ColorVectorSpace              0.0.2
 - Colors                        0.5.2
 - Compat                        0.6.0
 - Compose                       0.3.14
 - DataStructures                0.3.12
 - Dates                         0.3.2
 - FactCheck                     0.4.0
 - GeometricalPredicates         0.0.4
 - Graphics                      0.1.0
 - HDF5                          0.5.5
 - Homebrew                      0.1.16
 - HttpCommon                    0.1.2
 - IniFile                       0.2.4
 - Iterators                     0.1.8
 - JSON                          0.4.5
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.10.0
 - MacroTools                    0.2.0
 - Reexport                      0.0.2
 - Requires                      0.1.3
 - SHA                           0.1.1
 - SIUnits                       0.0.5
 - StatsFuns                     0.1.3
 - TexExtensions                 0.0.2
 - Tk                            0.3.6
 - URIParser                     0.0.7
 - Winston                       0.11.12
 - Zlib                          0.1.9
```

**Comment by dfdx** [comment]
I added some debug stuff, please checkout branch `debug-bounds-error`, launch multi.jl and post the output. From this output we will at least see what statement causes `BoundsError` and later track it up to the source of the problem.

**Comment by dchun** [comment]
I checked out the debug branch and I get the following output:

```
Warning: could not import Base.Text into Tk
size(A0) = (318780,)
size(dA0) = (4,)
size(mean_app) = (315,253,4)
processing color #1
processing color #2
processing color #3
processing color #4
elapsed time: 42.463713602 seconds (20526344268 bytes allocated, 47.23% gc time)
Sum of squared errors: 5973.675650349536
Sum of squared errors: 5224.417853590903
Sum of squared errors: 4448.197925821464
Sum of squared errors: 3947.244366758807
Sum of squared errors: 3485.38901220962
Sum of squared errors: 2977.2709803047915
Sum of squared errors: 2397.1097424310583
Sum of squared errors: 2031.401452761556
Sum of squared errors: 1828.4893701495398
Sum of squared errors: 1657.2915203130992
Sum of squared errors: 1523.8329781062453
Sum of squared errors: 1386.8480532922651
Sum of squared errors: 1171.1072599040958
Sum of squared errors: 926.4778504895065
Sum of squared errors: 754.4790611523375
Sum of squared errors: 661.8589280328192
Sum of squared errors: 629.0289631307882
Sum of squared errors: 613.6233312640842
Sum of squared errors: 602.3893186727211
Sum of squared errors: 594.636882731181
Sum of squared errors: 590.4470385078151
Sum of squared errors: 587.9622989398138
Sum of squared errors: 586.4104952343454
Sum of squared errors: 585.5347977719139
Sum of squared errors: 585.0549135840527
Sum of squared errors: 584.7861351239306
Sum of squared errors: 584.6363516258456
Sum of squared errors: 584.5572713174901
Sum of squared errors: 584.5206298100237
Sum of squared errors: 584.507909343844
elapsed time: 2.934364824 seconds (306281600 bytes allocated, 9.76% gc time)
ERROR: Cannot infer colorspace of Array, use an AbstractImage type
 in colorspace at /Users/davidchun/.julia/v0.3/Images/src/core.jl:684
 in properties at /Users/davidchun/.julia/v0.3/Images/src/core.jl:625
 in triplot at /Users/davidchun/.julia/v0.3/PiecewiseAffineTransforms/src/view.jl:15
 in anonymous at no file:15
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/davidchun/code/julia/aam/examples/multi.jl, in expression starting on line 9
```

**Comment by dfdx** [comment]
From this log it looks like you have images with 4 channels, but only images with 1 (grayscale) or 3 (RGB) channels are supported. Let's first confirm this is the case and, if so, find out how it happened. 

Please, run the following and post the result:  

```
using FaceDatasets

imgs = load_images(:cootes)
println("Number of images: $(length(imgs))")
println("Dimensions of images: $(size(imgs[1]))")
```

**Comment by dchun** [comment]
I have added the results of the `println` commands only for brevity:

```
julia> println("Number of images: $(length(imgs))")
Number of images: 26

julia> println("Dimensions of images: $(size(imgs[1]))")
Dimensions of images: (480,640,4)
```

Do you also need the output of the loaded images?

**Comment by dfdx** [comment]
> Do you also need the output of the loaded images?

It will pretty huge :) But serialized image may be helpful. Try the following:

```
using FaceDatasets
using HDF5

imgs = load_images(:cootes);
h5open("image.h5", "w") do file write(file, "I", imgs[1]) end

```

and send me resulting file "image.h5", please. 

My current guess is that `Images.imread()` returns additional channel (probably, transparency) on Mac OS, which results in images in Cootes dataset to have dimensions `(480, 640, 4)` instead of assumed `(480, 640, 3)`, which, in its turn, results in the error you have. In this case we can fix this problem by simply removing additional layer or converting to appropriate format.

**Comment by dchun** [comment]
You can download the file here: https://drive.google.com/file/d/0B8ltxUpD0as-dUVqSEdxd3pvM3M/view?usp=sharing

**Comment by dfdx** [comment]
I see that last channel is all ones in the image you sent me. I added a quick fix to a `master` branch that should fix this issue for you, so that you could continue working with AAMs. Later I'll add more robust fix. 

Let me know if latest `master` works for you now.

**Comment by dchun** [comment]
That seems to fix it. Thanks a lot.

However, although an error isn't generated from the script, the exception handler is now detecting the  BoundsError and returning it.

**Comment by dfdx** [comment]
Do you mean `BoundsError` during fitting later in the script? If so, then it's ok: being essentially Lucas-Kanade algorithm, AAM fitting can diverge and result in points out of an image, which results in a `BoundsError` of a different kind. Normally fitting diverges for me in 10-30% of cases when running `multi.jl`. The best way to fix it is to use initial shape which is close to expected one or just try several initial shapes. 

I'm still curious why you get 4-channel image. Could you please try the following commands in REPL and post the output:

```
using Images
path = Pkg.dir() * "/FaceDatasets/data/cootes/data/107_0764.bmp"
img = imread(path)
println(img)
sep = separate(img)
println(img)
arr = convert(Array, sep);
println(size(arr))
```

I believe either `imread()` or `separate()` add one channel, which may be a bug or undocumented feature. In both cases it would be nice to know it to be able to support cross-platform development of packages dependent on Images.jl.

**Comment by dchun** [comment]
Cool. Thanks for the tip.

Here's the output:

```
julia> img = imread(path)
RGB4 Image with:
  data: 640x480 Array{RGB4{UfixedBase{Uint8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> println(img)
RGB4 Image with:
  data: 640x480 Array{RGB4{UfixedBase{Uint8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> sep = separate(img)
RGB4 Image with:
  data: 480x640x4 Array{UfixedBase{Uint8,8},3}
  properties:
    colorspace: RGB4
    imagedescription: <suppressed>
    colordim: 3
    spatialorder:  y x
    pixelspacing:  1 1

julia> println(img)
RGB4 Image with:
  data: 640x480 Array{RGB4{UfixedBase{Uint8,8}},2}
  properties:
    imagedescription: <suppressed>
    spatialorder:  x y
    pixelspacing:  1 1

julia> arr = convert(Array, sep);

julia> println(size(arr))
(480,640,4)
```

Seems like it's the `separate()` function.  It seems to also be causing a similar issue when calling the `triplot()` function as well as the `view()` function which I just noticed while trying to run the example in the [PiecewiseAffineTransforms](https://github.com/dfdx/PiecewiseAffineTransforms.jl) package.

So when you call the `separate()` function, the colorspace property is RGB for you? What version of the Images package are you on? I am using v0.4.46

**Comment by dfdx** [comment]
In fact, `imread()` in your case already returns 4-channel color `RGB4`, while for me it's 3-channel `RGB`.   As far as I understand, Images.jl uses ImageMagick to perform IO operations, so this may be a difference in your and mine systems. 

I'm going to file an issue in Images.jl repo. Could you please tell me your OS version so that I could include it into the question?

**Comment by dchun** [comment]
Ahh. Didn't catch that.

I'm on OSX Yosemite v10.10.2 (14C1514)

ImageMagick 6.9.1-10 Q16 x86_64 2015-07-26
